name: IRC Server Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Zerotier
      run: |
        curl -s https://install.zerotier.com | sudo bash
        sudo zerotier-cli join ${{ secrets.ZEROTIER_NETWORK_ID }}
        sleep 10
        ZT_IP_ADDRESS=$(sudo zerotier-cli listnetworks | grep ${{ secrets.ZEROTIER_NETWORK_ID }} | awk '{print $NF}')
        echo "Zerotier IP Address: $ZT_IP_ADDRESS"

    - name: Pull Inspircd Docker image
      run: docker pull inspircd/inspircd

    - name: Run Inspircd container
      run: |
        docker run -d \
          --name inspircd \
          -e "SERVER_NAME=${{ secrets.SERVER_NAME }}" \
          -e "IP_ADDRESS=$ZT_IP_ADDRESS" \
          -p 6667:6667 \
          inspircd/inspircd

    - name: Pull Nginx Docker image
      run: docker pull nginx

    - name: Configure and run Nginx container
      run: |
        echo "events {} http { server { listen 80; server_name ${{ secrets.SERVER_NAME }}; location / { proxy_pass http://$ZT_IP_ADDRESS:6667; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto \$scheme; } } }" > nginx.conf
        docker run -d \
          --name nginx \
          -p 80:80 \
          -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro \
          nginx

    - name: Test IRC Server
      run: |
        sleep 10 # Wait for the server to start
        if nc -zv $ZT_IP_ADDRESS 6667; then
          echo "IRC server is running and reachable."
        else
          echo "Failed to connect to IRC server."
          exit 1
        fi